### ISSUE TITLE
Does not work correctly for EUR -> any and any->EUR

### ISSUE THREAD

**Issue by ichornukha** [vvaleri/converter#1]
1. Open app
![image](https://user-images.githubusercontent.com/6706350/95722920-384dcc00-0c7d-11eb-8442-3446cb9569c0.png)
2. Let inputs empty and select currency
![image](https://user-images.githubusercontent.com/6706350/95723093-6d5a1e80-0c7d-11eb-85fa-be0ce55a35fa.png)
3. Fill the first input. Scripts works, but not converts. 
![image](https://user-images.githubusercontent.com/6706350/95723204-8ebb0a80-0c7d-11eb-9646-9cacbfa45912.png)

**Comment by vvaleri** [comment]
thanks, now it's working
![eurusd](https://user-images.githubusercontent.com/66499128/95767167-de143180-0ca3-11eb-815e-5baa95b6978e.png)
![usdeur](https://user-images.githubusercontent.com/66499128/95767172-e3717c00-0ca3-11eb-8f6d-32f788a37063.png)

**Comment by ichornukha** [comment]
Thank you for fix
